joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
base_pendulum_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_pendulum_roll_joint
    pid: {p: 3000.0, i: 000.00, d: 000.0, antiwindup: True}